excerpt_separator: ""
highlighter: rouge
markdown: kramdown
title: swannysec
tagline: Musings on InfoSec
description: Documenting my thoughts on security, professional development, and whatever else comes to mind.
paginate: 5
url: https://swannysec.net
enforce_ssl: www.swannysec.net
gems:
  - jekyll-seo-tag

