excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://swannysec.github.io
title: swannysec
tagline: Musings on InfoSec
description: Documenting my thoughts on security, professional development, and whatever else comes to mind.
paginate: 5
